Update README.md
HappyFerret/tennis-test pull request #1
Opened 2021-05-05 16:19 UTC by json-born

2021-05-05 16:24 UTC, digitalgears commented on README.md
> +
```suggestion
- Does anyone actually read this far?
```

2021-05-05 16:25 UTC, pstonham approved these changes

2021-05-05 18:30 UTC, jeffwad requested changes
Mwah ha ha! I still has access...

2021-05-05 18:31 UTC, jeffwad commented
Feel free to remove my account/email address from this repo.

2021-05-06 08:13 UTC, thardyman commented on README.md
> +- The score resets to 0-0 when one player reaches 40.
Does it?

2021-05-06 08:16 UTC, thardyman commented on README.md
> +- The score resets to 0-0 if one player scores twice in a row at Deuce
Again, the scenario is a win...
```suggestion
- If one player scores twice in a row at Deuce then they win the game
```

2021-05-06 08:16 UTC, thardyman approved these changes

2021-05-06 08:17 UTC, thardyman commented
> Feel free to remove my account/email address from this repo.

Lol, thanks for letting us know!

2021-05-06 08:51 UTC, merged